# Builds & pushes a docker image when a tag is created.
# Tag pattern: '[tag]' & '[tag]-classic'
# 'latest' & 'classic' also, when master tagged.

# Only pushes the tag when it matches one of the following patterns:
# X, X.Y or X.Y.Z

name: Build and push docker (tag)

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+'                 # X
      - '[0-9]+\.[0-9]+'         # X.Y
      - '[0-9]+\.[0-9]+\.[0-9]+' # X.Y.Z

jobs:
  setup-build-environment:
    uses: ./.github/workflows/setup-build-environment.yaml

  docker-login:
    uses: ./.github/workflows/docker-login.yaml
    secrets: inherit

  build-and-publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Set tag env
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Is branch "master"?
        if: ${{ env.SHAIRPORT_SYNC_BRANCH == 'master' }}
        run: echo "LATEST_TAG=true" >> $GITHUB_ENV

      - name: Build and push (classic)
        uses: docker/build-push-action@v6.13.0
        with:
          context: ./
          file: ./docker/classic/Dockerfile
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          tags: |
            ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.GIT_TAG }}-classic
            ${{ env.LATEST_TAG == 'true' && format('{0}:classic', secrets.DOCKER_IMAGE_NAME) || '' }}
          build-args: |
            SHAIRPORT_SYNC_BRANCH=${{ env.SHAIRPORT_SYNC_BRANCH }}
 
      - name: Build and push
        uses: docker/build-push-action@v6.13.0
        with:
          context: ./
          file: ./docker/Dockerfile
          platforms: ${{ env.DOCKER_PLATFORMS }}
          push: true
          tags: |
            ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.GIT_TAG }}
            ${{ env.LATEST_TAG == 'true' && format('{0}:latest', secrets.DOCKER_IMAGE_NAME) || '' }}
          build-args: |
            SHAIRPORT_SYNC_BRANCH=${{ env.SHAIRPORT_SYNC_BRANCH }}
            NQPTP_BRANCH=${{ env.NQPTP_BRANCH }}
